### ISSUE TITLE
Switch to using cf-graph-countyfair for pypi -> conda forge mapping

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight-Labs/beni#12]
I [recently heard about](https://github.com/Quansight/Quansight.github.io/discussions/44#discussioncomment-1254965) the [Grayskull](https://github.com/conda-incubator/grayskull) package, from @ForgottenProgramme, which can automatically generate a Conda forge package from a PyPi package. @jaimergp mentioned that they [use cf-graph-countyfair](https://github.com/regro/cf-graph-countyfair/tree/master/mappings/pypi) to maintain a mapping between PyPi and conda forge package names. Beni could use this to perform its mapping as well, since often the PyPi and conda forge name are different.

**Comment by flying-sheep** [comment]
Good idea! I started something in #13
