### ISSUE TITLE
Allow selection of extras or flit’s deps

### ISSUE THREAD

**Issue by flying-sheep** [Quansight-Labs/beni#3]
Currently beni just adds all extra dependencies.

It would be great to have the same behavior as flit: `--deps=all` by default, and the ability to specify r.g. `--deps=develop` or individual `--extras` to filter the requirements (`packaging.requirements.Requirement` allows accessing the `extra` that requirement is part of)

**Comment by flying-sheep** [comment]
@saulshanabrook well? would you consider it if I made a PR?

**Comment by saulshanabrook** [comment]
Sorry wasn't watching this repo! Yeah that would be great.
