### ISSUE TITLE
Maybe add me on PyPI

### ISSUE THREAD

**Issue by flying-sheep** [Quansight-Labs/beni#7]
Hia! Since you added me to this project, maybe you’d like to consider to also add me to the PyPI maintainers for it? https://pypi.org/user/flyingsheep/

**Comment by saulshanabrook** [comment]
Yep, thanks for the ping, I just added you asn an owner!

It's great to have your help on this project, thank you!

**Comment by flying-sheep** [comment]
Perfect, thank you. I published 0.4.0 with the CLI changes (and then immediately 0.4.1 because I also wanted to add `description-file = "README.md"` so it has a description on PyPI)
